config/routes.rb
Rails.application.routes.draw do

  get 'messages/reply'
  root "bases#index"
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get "/base", to: "base#index"
  resources :bases
  post "/bases/sendMessage", to: "bases#sendMessage"
  post "/bases/Choice", to: "bases#Choice"
 
  get 'messages/inbox'
  get 'messages/convo'
  post "/messages/inbox", to: "messages#inbox"
  post "/messages/convo", to: "messages#convo"
  post "/messages/sendMessage", to: "messages#sendMessage"
  post "/messages/convoMessage", to: "messages#convoMessage"

  resources :posts

  
  resource :messages do 
    resources :conversations
    collection do
      post 'reply'
    end
    post "/messages/display", to: "messages#display"
  end
end

app/controllers/messages_controller.rb
require 'Airtable'
require 'twilio-ruby'

class MessagesController < ApplicationController 
  skip_before_action :verify_authenticity_token
 #skip_before_action :authenticate_user!, :only => "reply"


  def reply
    message_body = params["Body"]
    from_number = params["From"]
    boot_twilio
    sms = @client.messages.create(
      from: '+12057973744',
      to: from_number,
      body: "Hello there, thanks for texting me. Your number is #{from_number}."
    
    )
  end




  
  def display
    boot_twilio

    bootAirtable

    @table = @Client.table("appacJ0nJ0C1wijg2","table3")
    
    allMessages = @client.messages.list(limit: 20)

    allMessages.each do |record|
      @newRecord = Airtable::Record.new(:Body => record.body, :To => record.to, :From => record.from)
      @table.create(@newRecord)

      # puts " "
      # puts "Body:"
      # puts record.body
      # puts "To:"
      # puts record.to
      # puts "From:"
      # puts record.from
      
    end

    def sendMessage

      boot_twilio                                                #Boots twilio, calls twilio function to create a new message, passing the message body params, reciever phone params, and sender phone params....
      @message = @client.messages.create(                        #...and sends the message...
        :body => (body_params),
          
        :to => '+1' + (phone_params),   
            
        from: @twilio_number  
      )  
      
      redirect_to :bases
        
    end
    

  end

  
  def body_params                                                   #Passes message body :text from form as a parameter
    params.require(:text)
  end

  def phone_params                                                  #Passes phone number :number from form as param
    params.require(:number)
  end
  
  def convoMessage

    boot_twilio                                                #Boots twilio, calls twilio function to create a new message, passing the message body params, reciever phone params, and sender phone params....
    @message = @client.messages.create(                        #...and sends the message...
      :body => (body_params),
        
      :to => '+1' + (phone_params),   
          
      from: '+12057973744'
    )
    redirect_to :messages
      
  end

  def convo           #Conversation Method

    @keyparams = params.require(:key)
    @valueparams = params.require(:value)
    #catching the key and value parameters passed by inbox, storing as global variables to be used by the convo view

  end

  def inbox

    boot_twilio
    @allMessages = @client.messages.list 

    @phoneHash = {}

    @allMessages.each do |record|
      # if record.to or record.from includes specific number then 
      #   need date/time to and from
      #   calls = @client.calls.list(status: 'busy', to: '+15558675310', limit: 20)      
      if record.from != "+12057973744"

        if @phoneHash.length == 0 

          key = record.from
          val = record.body
          convoArray = []
          convoArray << val
          @phoneHash.store(key,convoArray)
          

        elsif @phoneHash.include? record.from

          key = record.from
          val = record.body
          @phoneHash[key] << val

        else

          key = record.from
          val = record.body
          convoArray = []
          @phoneHash.store(key,convoArray)
          convoArray << val

        end

      end

    end


    
  end

  private
 
  def boot_twilio
    account_sid ='AC4158ba2bf41e0195d9a2603efc32871c'
    auth_token = 'a77f06b3dfb39d2732cad851f31faae3'
    twilio_number = '+12057973744'
    @client = Twilio::REST::Client.new account_sid, auth_token
  end

  def bootAirtable
    @Client = Airtable::Client.new("keyr6sRq2AAXV9ash")
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/convo.html.erb
<header>
 
        <div class = "button_container">
            <div class = "Inboxbutton">
                <%= link_to "INBOX", "/messages/inbox", class: "button" %>
            </div>
            
            <div class = "sendMessagebutton">
                <%= link_to "Send Messages", "/", class: "button" %>
            </div>
        </div>

   <div class = "logo_container">
        <img src = "edensfarmlogo.png" alt= "eden's farm logo" width = "150" height = "150">
    </div>

</header>

<body>
    <div class="container">

        <div class = "new_reply">
        <%=@keyparams%>                             <%#printing the key params (the phone number we just clicked on in inbox)%>
        </div>

        <div><br>
        <%@valueparams.each do |i|%><br>                <%# Looping over the values in valueparams to display all the messages sent by that phone number%>
            <div class = "received">
            <%= i%>
            </div><br>
        <%end%>
        </div><br>
        <div class = "sent"><br>
        Message 1
        
        </div>

        <div class = "new_reply"><br><br>
        <%= form_with url:"/messages/convoMessage", method: :post do |form| %>
             <%=form.label :choice_specific, "Reply" %>
                <%=form.text_field :number %>
                <%= form.label "Reply" %><br>
                <%= form.text_field :text %><br>

            <%= form.submit 'Send' %>

        <%end%>
        </div>
    </div>
</body>

app/views/messages/inbox.html.erb
<header>
 
        <div class = "button_container">
            <div class = "Inboxbutton">
                <%= link_to "INBOX", "/messages/inbox", class: "button" %>
            </div>
            
            <div class = "sendMessagebutton">
                <%= link_to "Send Messages", "/", class: "button" %>
            </div>
        </div>

   <div class = "logo_container">
        <img src = "edensfarmlogo.png" width = "150" height = "150">
    </div>

</header>

<body>
    <div class="container">

       

        
            <%@phoneHash.each do |key, value|%>                         <%#Loop over every key and value in the phoneHash%>
            <div class = "message_container">
            <%=key%>                                               <%#Print the key (the phone number%>
        
            <%=link_to value[0], messages_convo_path(:key => key, :value => value)%>  
            <%#print the first element of value(the most recent message) as a link, pass key and value array as params to messages controller)%>
            </div>
            <% end %>
        

    
       
    
    </div>
</body>

app/views/messages/reply.html.erb
<h1>Messages#reply</h1>
<p>Find me in app/views/messages/reply.html.erb</p>